export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git)

# Remove duplicate sourcing of aliases, funcs, env (already handled below)
# source $HOME/.shell/.aliases
# source $HOME/.shell/.funcs
# source $HOME/.shell/.env

# Profile zsh startup
zmodload zsh/zprof

source $ZSH/oh-my-zsh.sh

# Add Git completion
zstyle ':completion::compinit' rehash true
autoload -Uz compinit
compinit -C

# Optionally, disable compaudit security check (less secure, but faster)
# ZSH_DISABLE_COMPAUDIT=true
# export ZSH_DISABLE_COMPAUDIT

setopt autocd

# Set vim to default editor
export EDITOR='vim'

if typeset -f nvm > /dev/null; then
  # Automatically switch node versions when a directory has a `.nvmrc` file
  autoload -U add-zsh-hook
  # Zsh hook function
  load-nvmrc() {
  local node_version="$(nvm version)" # Current node version
  local nvmrc_path="$(nvm_find_nvmrc)" # Path to the .nvmrc file

    # Check if there exists a .nvmrc file
    if [ -n "$nvmrc_path" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    # Check if the node version in .nvmrc is installed on the computer
    if [ "$nvmrc_node_version" = "N/A" ]; then
      # Install the node version in .nvmrc on the computer and switch to that node version
      nvm install
      # Check if the current node version matches the version in .nvmrc
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      # Switch node versions
      nvm use
    fi
    # If there isn't an .nvmrc make sure to set the current node version to the default node version
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
    fi
  }
# Add the above function when the present working directory (pwd) changes
add-zsh-hook chpwd load-nvmrc
load-nvmrc
fi

# --- Custom logic for dotfiles portability ---
# Detect Git Bash on Windows
if [[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* ]]; then
  export DOTFILES_OS="gitbash"
else
  export DOTFILES_OS="unix"
fi

# Source dotfiles shell files if present
[ -f $HOME/.shell/.aliases ] && source $HOME/.shell/.aliases
[ -f $HOME/.shell/.env ] && source $HOME/.shell/.env
[ -f $HOME/.shell/.funcs ] && source $HOME/.shell/.funcs

# Only run ulimit on non-Windows
if [[ "$DOTFILES_OS" != "gitbash" ]]; then
  ulimit -c 256
fi

# Powerline for zsh (adjust path if needed)
if [ -f /etc/fedora-release ]; then
  [ -f /usr/share/powerline/zsh/powerline.zsh ] && source /usr/share/powerline/zsh/powerline.zsh
elif [ -f /etc/debian-release ]; then
  [ -f /usr/share/powerline/bindings/zsh/powerline.zsh ] && source /usr/share/powerline/bindings/zsh/powerline.zsh
fi

# Fun prompt if TERMINOLOGY is set
if [[ "$TERMINOLOGY" -eq "1" ]]; then
    pokemon
fi

# Use Spaceship prompt
autoload -U promptinit; promptinit
# prompt spaceship

setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell

unset LESS;