export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# plugins=(git)
source $ZSH/oh-my-zsh.sh

source $HOME/.shell/.aliases
source $HOME/.shell/.funcs

# Add Git completion
autoload -Uz compinit && compinit

setopt autocd

# Set vim to default editor
export EDITOR='vim'
