#!/bin/bash -x
# Stolen from http://abesto.net/journaling-for-geeks/
# Thanks Zoltán Nagy!

diary_editor=${DIARY_EDITOR:-"/usr/bin/vim"}
file=${DIARY_FILE:-"$HOME/Documents/diary.gpg"}
if [ "$DIARY_SYMMETRIC" == "yes" ]; then
  encrypt='--symmetric'
else
  encrypt='--encrypt'
fi
tmp=`mktemp`
cp "$file" "$tmp" && gpg --output "$tmp" --decrypt --yes "$file" && "$diary_editor" "$tmp" && gpg --output "$file" $encrypt --yes "$tmp"
rm "$tmp"
