#!/bin/bash

# Screensaver
if [ ! -d "$HOME/src/cantera-lock" ]; then
  cd $HOME/src
  git clone https://github.com/scanf/cantera-lock.git 
  cd cantera-lock/
  autoreconf -i
  ./configure
  make
  make install 
fi

# Terminal
if [ ! -d "$HOME/src/cantera-term" ]; then
  cd $HOME/src
  git clone https://github.com/mortehu/cantera-term 
  cd cantera-term/ 
  autoreconf -i
  ./configure
  make
  make install
fi

# Video downloader
if [ ! -d "$HOME/src/cc-y-download" ]; then
  cd $HOME/src
  git clone https://github.com/scanf/cc-y-download
fi

# Installation tool
if [ ! -d "$HOME/src/atsign" ]; then
  cd $HOME/src
  git clone https://github.com/mastensg/atsign/
  echo "source ~/src/atsign/atsign.sh" >> ~/.bashrc
fi
