set nocompatible              " be iMproved, required
set number
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/src/github.com/VundleVim/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'Raimondi/delimitMate'
Plugin 'Yggdroot/indentLine'
Plugin 'adragomir/javacomplete'
Plugin 'bpdp/vim-java'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'flazz/vim-colorschemes'
Plugin 'gmarik/Vundle.vim'
Plugin 'gorkunov/smartgf.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tfnico/vim-gradle'
Plugin 'tpope/vim-fireplace'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-markdown'
Plugin 'vivien/vim-addon-linux-coding-style'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" vertical line indentation
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#09AA08'
let g:indentLine_char = '│'

set encoding=utf-8
let loaded_matchparen = 1
let g:js_indent_log = 0
syntax on
" autocmd BufWritePre *.cc,*.c,*.h %s/  *$//eg
map ;<Space> :w !~/bin/giver<CR>

map <Down> gj
map <Up>   gk

set tags=tags;/
set bg=dark
set is
set ai
set aw
set noerrorbells
set novisualbell
set ts=8
set sts=2
set sw=2
set et
set modelines=2
set completeopt=preview
set nofoldenable
set mouse=
set cino=:0
set shiftround
set title

" source ~/.vim/cppcomplete.vim

ab helol hello
ab fpritnf fprintf
ab fpitnf  fprintf

map Q :echo "You pressed Q"<CR>

" map  <Esc>xpa
" imap  <Esc>xpa

map  <Esc>:tabnew<CR>
map <F1> 1gt
map <F2> 2gt
map <F3> 3gt
map <F4> 4gt
map <F5> 5gt
map <F6> 6gt
map <F7> 7gt
map <F8> 8gt
map <F9> 9gt
map <F10> 10gt
imap <F1> <Esc>1gta
imap <F2> <Esc>2gta
imap <F3> <Esc>3gta
imap <F4> <Esc>4gta
imap <F5> <Esc>5gta
imap <F6> <Esc>6gta
imap <F7> <Esc>7gta
imap <F8> <Esc>8gta
imap <F9> <Esc>9gta
imap <F10> <Esc>10gta

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

set guioptions=
set guicursor=i:block-Cursor
set guifont=DejaVu\ Sans\ Mono\ 12
highlight Normal     guifg=gray guibg=black

map  :echo "You pressed Ctrl-O"<CR>

autocmd BufWritePre *.{C,cc,cpp,c,java,h} silent! %s/[ \t]\+$//
"autocmd BufRead *.{C,cc,cpp,c,java,h} silent! %s/[ \t]\+$//
autocmd BufNewFile,BufRead *.m set syntax=objc
autocmd BufNewFile,BufRead *.m call GnuIndent()

hi TabLineSel term=reverse ctermfg=white ctermbg=lightblue guifg=white guibg=blue

function! GnuIndent()
  setlocal cinoptions=>4,n-2,{2,^-2,:2,=2,g0,h2,p5,t0,+2,(0,u0,w1,m1
  setlocal shiftwidth=2
  setlocal tabstop=8
endfunction

au FileType c,cc call GnuIndent() 

" cmap w!! w !sudo tee % >/dev/null

" vdrift
"set sts=8 sw=8 noet cinoptions=
let NERDTreeShowHidden=1
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
