source $HOME/.term/.aliases
source $HOME/.term/.funcs
source $HOME/.term/.env

ulimit -c unlimited

source $HOME/src/github.com/scanf/liquidprompt/liquidprompt
#source ~/src/atsign/atsign.sh
source $HOME/.git-completion.bash
