source ~/.bashrc
eval "$(rbenv init -)"
source ~/.swift-package-complete.bash

export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
