# Debian packaging
export DEBFULLNAME=Alexander\ Alemayhu
export DEBEMAIL=alexander@bitraf.no

# Locale
export LANGUAGE=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

# Git
alias gitlog='git log -10 --graph --date-order -C -M --pretty=format:"%C(yellow)%h%C(reset) - %C(bold green)%ad%C(reset) - %C(dim yellow)%an%C(reset) %C(bold red)>%C(reset) %C(white)%s%C(reset) %C(bold red)%d%C(reset) " --abbrev-commit --date=short'
alias gic='git clone'
alias gip='git push'
alias git-amn='git ci -v --amend'
alias gc='git commit -v'
alias ga='git add -p'
alias gs='git status -s'
alias gss='git status -s'

function gp () {
  git push all --all
  git push all --tags
}

# golang
export GOPATH="$HOME"/opt/og
export GOROOT="$HOME"/opt/go

for i in "$HOME"/opt/*/bin
do
PATH="$PATH:$i"
done

# Stuff

ulimit -c unlimited
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias reload='source ~/.bashrc'

source $HOME/src/github/nojhan/liquidprompt.git/liquidprompt
#source ~/src/atsign/atsign.sh
alias ii='sudo apt-get install'
alias batch_resize_jpg='for i in $( ls *.jpg); do convert -resize 50% $i re_$i; done'
alias cs='ssh alemayhu.com'
alias apt-all='sudo apt-get update && sudo apt-get upgrade && sudo apt-get autoclean'
alias latest-log='tail -f $( ls -1tr `find . -name "*.log"` | tail -1 )'
alias ccdate='date +"%A, %d. %B %Y"'
alias pyserve='python -m SimpleHTTPServer'

source $HOME/.git-completion.bash

function adb-screenshot()
{
echo $1
exit
adb shell screencap -p /sdcard/$1
adb pull /sdcard/$1
adb shell rm /sdcard/$1
}

linz()
{
  mkdir -p $HOME/tmp
  filename=$(basename `pwd`)
  lintian > "$HOME/tmp/$filename-lintian.log"
}

rdvid()
{
files=(./*)
video="${files[RANDOM % ${#files[@]}]}"
mplayer -fs "$video"
read -p "Would you like to delete $video?(n/y)" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  rm "$video"
  echo
  echo "$video is deleted."
fi
}

vimr()
{
  URL=$1
  SUFFIX=$(basename $URL)
  SHA=`echo $URL | shasum`
  FILENAME=${SHA//[[:blank:]]/}.$SUFFIX
  DOWNLOAD_PATH=/tmp/$FILENAME

  if [ ! -f $DOWNLOAD_PATH ]; then
    wget "$URL" -O "$DOWNLOAD_PATH"
  fi

  vim $DOWNLOAD_PATH
}
