# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="wedisagree"
CASE_SENSITIVE="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git)
source $ZSH/oh-my-zsh.sh
source $HOME/src/github/nojhan/liquidprompt.git/liquidprompt.plugin.zsh
source $HOME/.aliases
source $HOME/.funcs
source $HOME/.env
