#!/bin/bash
	
cd /home/ccscanf/src 
git clone https://github.com/scanf/hest.git 
cd hest/ 
autoreconf -i 
./configure 
make 
make install && cd /home/ccscanf/src 
git clone https://github.com/scanf/cantera-lock.git 
cd cantera-lock/ 
autoreconf -i 
./configure 
make 
make install 
cd /home/ccscanf/src 
git clone https://github.com/mortehu/cantera-term 
cd cantera-term/ 
autoreconf -i 
./configure 
make 
make install
