PATH=~/src/xpmsvol:$PATH

PATH=$PATH:~/src/dmenu
PATH=$PATH:~/src/xbindkeys
PATH=$PATH:~/opt/bin

xrdb ~/.Xdefaults

hostname | grep ifi >/dev/null && setxkbmap us || setxkbmap us altgr-intl
setxkbmap -option ctrl:nocaps
setxkbmap -option terminate:ctrl_alt_bksp
xset r on
xset -b

xinput set-prop 12 "Device Enabled" 0

nitrogen --restore

pkill gnome-terminal
pkill ssh-agent
pkill unclutter
pkill xpmsvol

xbindkeys -p || xbindkeys

xscreensaver -no-capture-stderr -no-splash &
xpmsvol

awesome
test -f /usr/bin/urxvt && urxvt -geometry 234x50 || xterm -geometry 234x50
